services:
  postgres-carniceria:
    image: postgres:latest
    container_name: gestion-carniceria-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: gestion_carniceria
      PGTZ: UTC
    ports:
        - "5432:5432"
    restart: unless-stopped